name: deploy

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy:
    name: Node.js v16
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: npm ci

      - name: Upload secrets to Wrangler
        run: |
          echo $KB_EMAIL | npx wrangler secret put KB_EMAIL
          echo $KB_PASSWORD | npx wrangler secret put KB_PASSWORD
        env:
          KB_EMAIL: ${{ secrets.KB_EMAIL }}
          KB_PASSWORD: ${{ secrets.KB_PASSWORD }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy
        run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
